package pokemon.util;

import java.util.HashMap;
import java.util.Map;

public class AbilityAndDescription {
    private static Map<String, String> abilities = new HashMap<>();
    static {
	abilities.put("Wonder_Guard", "Only supereffective moves will hit.");
	abilities.put("White_Smoke", "Prevents other Pokémon from lowering its stats.");
	abilities.put("Water_Veil", "Prevents the Pokémon from getting a burn.");
	abilities.put("Water_Absorb", "Restores HP if hit by a Water-type move.");
	abilities.put("Volt_Absorb", "Restores HP if hit by an Electric-type move.");
	abilities.put("Vital_Spirit", "Prevents the Pokémon from falling asleep.");
	abilities.put("Truant", "Pokémon can't attack on consecutive turns.");
	abilities.put("Trace", "The Pokémon copies a foe's Ability.");
	abilities.put("Torrent", "Powers up Water-type moves in a pinch.");
	abilities.put("Thick_Fat", "Ups resistance to Fire- and Ice-type moves.");
	abilities.put("Synchronize", "Passes a burn, poison, or paralysis to the foe.");
	abilities.put("Swift_Swim", "Boosts the Pokémon's Speed in rain.");
	abilities.put("Swarm", "Powers up Bug-type moves in a pinch.");
	abilities.put("Suction_Cups", "Negates all moves that force switching out.");
	abilities.put("Sturdy", "It cannot be knocked out with one hit.");
	abilities.put("Sticky_Hold", "Protects the Pokémon from item theft.");
	abilities.put("Stench", "The stench may cause the target to flinch.");
	abilities.put("Static", "Contact with the Pokémon may cause paralysis.");
	abilities.put("Speed_Boost", "Its Speed stat is gradually boosted.");
	abilities.put("Soundproof", "Gives immunity to sound-based moves.");
	abilities.put("Shield_Dust", "Blocks the added effects of attacks taken.");
	abilities.put("Shell_Armor", "The Pokémon is protected against critical hits.");
	abilities.put("Shed_Skin", "The Pokémon may heal its own status problems.");
	abilities.put("Shadow_Tag", "Prevents the foe from escaping.");
	abilities.put("Serene_Grace", "Boosts the likelihood of added effects appearing.");
	abilities.put("Sand_Veil", "Boosts the Pokémon's evasion in a sandstorm.");
	abilities.put("Sand_Stream", "The Pokémon summons a sandstorm in battle.");
	abilities.put("Run_Away", "Enables a sure getaway from wild Pokémon.");
	abilities.put("Rough_Skin", "Inflicts damage to the attacker on contact.");
	abilities.put("Rock_Head", "Protects the Pokémon from recoil damage.");
	abilities.put("Rain_Dish", "The Pokémon gradually regains HP in rain.");
	abilities.put("Pure_Power", "Raises the Pokémon's Attack stat.");
	abilities.put("Pressure", "The Pokémon raises the foe's PP usage.");
	abilities.put("Poison_Point", "Contact with the Pokémon may poison the attacker.");
	abilities.put("Plus", "Ups Sp. Atk if another Pokémon has Plus or Minus.");
	abilities.put("Pickup", "The Pokémon may pick up items.");
	abilities.put("Own_Tempo", "Prevents the Pokémon from becoming confused.");
	abilities.put("Overgrow", "Powers up Grass-type moves in a pinch.");
	abilities.put("Oblivious", "Prevents it from becoming infatuated.");
	abilities.put("Natural_Cure", "All status problems heal when it switches out.");
	abilities.put("Minus", "Ups Sp. Atk if another Pokémon has Plus or Minus.");
	abilities.put("Marvel_Scale", "Ups Defense if there is a status problem.");
	abilities.put("Magnet_Pull", "Prevents Steel-type Pokémon from escaping.");
	abilities.put("Magma_Armor", "Prevents the Pokémon from becoming frozen.");
	abilities.put("Liquid_Ooze", "Damages attackers using any draining move.");
	abilities.put("Limber", "The Pokémon is protected from paralysis.");
	abilities.put("Lightning_Rod", "Draws in all Electric-type moves to up Sp. Attack.");
	abilities.put("Levitate", "Gives immunity to Ground type moves.");
	abilities.put("Keen_Eye", "Prevents other Pokémon from lowering accuracy.");
	abilities.put("Intimidate", "Lowers the foe's Attack stat.");
	abilities.put("Insomnia", "Prevents the Pokémon from falling asleep.");
	abilities.put("Inner_Focus", "The Pokémon is protected from flinching.");
	abilities.put("Immunity", "Prevents the Pokémon from getting poisoned.");
	abilities.put("Illuminate", "Raises the likelihood of meeting wild Pokémon.");
	abilities.put("Hyper_Cutter", "Prevents other Pokémon from lowering Attack stat.");
	abilities.put("Hustle", "Boosts the Attack stat, but lowers accuracy.");
	abilities.put("Huge_Power", "Raises the Pokémon's Attack stat.");
	abilities.put("Guts", "Boosts Attack if there is a status problem.");
	abilities.put("Forecast", "Castform transforms with the weather.");
	abilities.put("Flash_Fire", "It powers up Fire-type moves if it's hit by one.");
	abilities.put("Flame_Body", "Contact with the Pokémon may burn the attacker.");
	abilities.put("Effect_Spore", "Contact may poison or cause paralysis or sleep.");
	abilities.put("Early_Bird", "The Pokémon awakens quickly from sleep.");
	abilities.put("Drought", "Turns the sunlight harsh when the Pokémon enters a battle.");
	abilities.put("Drizzle", "The Pokémon makes it rain when it enters a battle.");
	abilities.put("Damp", "Prevents the use of self-destructing moves.");
	abilities.put("Cute_Charm", "Contact with the Pokémon may cause infatuation.");
	abilities.put("Compound_Eyes", "The Pokémon's accuracy is boosted.");
	abilities.put("Color_Change", "Changes the Pokémon's type to the foe's move.");
	abilities.put("Cloud_Nine", "Eliminates the effects of weather.");
	abilities.put("Clear_Body", "Prevents other Pokémon from lowering its stats.");
	abilities.put("Chlorophyll", "Boosts the Pokémon's Speed in sunshine.");
	abilities.put("Blaze", "Powers up Fire-type moves in a pinch.");
	abilities.put("Battle_Armor", "The Pokémon is protected against critical hits.");
	abilities.put("Arena_Trap", "Prevents the foe from fleeing.");
	abilities.put("Air_Lock", "Eliminates the effects of weather.");
	abilities.put("Unburden", "Raises Speed if a held item is used.");
	abilities.put("Unaware", "Ignores any stat changes in the Pokémon.");
	abilities.put("Tinted_Lens", "Powers up “not very effective” moves.");
	abilities.put("Technician", "Powers up the Pokémon's weaker moves.");
	abilities.put("Tangled_Feet", "Raises evasion if the Pokémon is confused.");
	abilities.put("Super_Luck", "Heightens the critical-hit ratios of moves.");
	abilities.put("Storm_Drain", "Draws in all Water-type moves to up Sp. Attack.");
	abilities.put("Steadfast", "Raises Speed each time the Pokémon flinches.");
	abilities.put("Stall", "The Pokémon moves after all other Pokémon do.");
	abilities.put("Solid_Rock", "Reduces damage from supereffective attacks.");
	abilities.put("Solar_Power", "In sunshine, Sp. Atk is boosted but HP decreases.");
	abilities.put("Snow_Warning", "The Pokémon summons a hailstorm in battle.");
	abilities.put("Snow_Cloak", "Raises evasion in a hailstorm.");
	abilities.put("Sniper", "Powers up moves if they become critical hits.");
	abilities.put("Slow_Start", "Temporarily halves Attack and Speed.");
	abilities.put("Skill_Link", "Increases the frequency of multi-strike moves.");
	abilities.put("Simple", "Doubles all stat changes.");
	abilities.put("Scrappy", "Enables moves to hit Ghost-type Pokémon.");
	abilities.put("Rivalry", "Deals more damage to a Pokémon of same gender.");
	abilities.put("Reckless", "Powers up moves that have recoil damage.");
	abilities.put("Quick_Feet", "Boosts Speed if there is a status problem.");
	abilities.put("Poison_Heal", "Restores HP if the Pokémon is poisoned.");
	abilities.put("Normalize", "All the Pokémon's moves become the Normal type.");
	abilities.put("No_Guard", "Ensures attacks by or against the Pokémon land.");
	abilities.put("Multitype", "Changes type to match the held Plate.");
	abilities.put("Motor_Drive", "Raises Speed if hit by an Electric-type move.");
	abilities.put("Mold_Breaker", "Moves can be used regardless of Abilities.");
	abilities.put("Magic_Guard", "The Pokémon only takes damage from attacks.");
	abilities.put("Leaf_Guard", "Prevents problems with status in sunny weather.");
	abilities.put("Klutz", "The Pokémon can't use any held items.");
	abilities.put("Iron_Fist", "Boosts the power of punching moves.");
	abilities.put("Ice_Body", "The Pokémon gradually regains HP in a hailstorm.");
	abilities.put("Hydration", "Heals status problems if it is raining.");
	abilities.put("Honey_Gather", "The Pokémon may gather Honey from somewhere.");
	abilities.put("Heatproof", "Weakens the power of Fire-type moves.");
	abilities.put("Gluttony", "Encourages the early use of a held Berry.");
	abilities.put("Frisk", "The Pokémon can check a foe's held item.");
	abilities.put("Forewarn", "Determines what moves a foe has.");
	abilities.put("Flower_Gift", "Powers up party Pokémon when it is sunny.");
	abilities.put("Filter", "Reduces damage from supereffective attacks.");
	abilities.put("Dry_Skin", "Reduces HP if it is hot. Water restores HP.");
	abilities.put("Download", "Adjusts power according to a foe's defenses.");
	abilities.put("Bad_Dreams", "Reduces a sleeping foe's HP.");
	abilities.put("Anticipation", "Senses a foe's dangerous moves.");
	abilities.put("Anger_Point", "Maxes Attack after taking a critical hit.");
	abilities.put("Aftermath", "Damages the attacker landing the finishing hit.");
	abilities.put("Adaptability", "Powers up moves of the same type.");
    }
}
